#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TODOList.Android.Resource", IsApplication=true)]

namespace TODOList.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PCLCrypto.Resource.String.ApplicationName = global::TODOList.Android.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::TODOList.Android.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::TODOList.Android.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::TODOList.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int com_facebook_auxiliary_view_position = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int com_facebook_confirm_logout = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int com_facebook_foreground_color = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int com_facebook_horizontal_alignment = 2130771973;
			
			// aapt resource value: 0x7f01000b
			public const int com_facebook_is_cropped = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int com_facebook_login_text = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int com_facebook_logout_text = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int com_facebook_object_id = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int com_facebook_object_type = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int com_facebook_preset_size = 2130771978;
			
			// aapt resource value: 0x7f010003
			public const int com_facebook_style = 2130771971;
			
			// aapt resource value: 0x7f010009
			public const int com_facebook_tooltip_mode = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int com_facebook_blue = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int com_facebook_button_background_color = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int com_facebook_button_background_color_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int com_facebook_button_background_color_pressed = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int com_facebook_button_like_background_color_selected = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int com_facebook_button_login_silver_background_color = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int com_facebook_button_login_silver_background_color_pressed = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int com_facebook_button_send_background_color = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int com_facebook_button_send_background_color_pressed = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int com_facebook_likeboxcountview_border_color = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int com_facebook_likeboxcountview_text_color = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int com_facebook_likeview_text_color = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int com_facebook_share_button_text_color = 2131034124;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int com_facebook_likeboxcountview_border_radius = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int com_facebook_likeboxcountview_border_width = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int com_facebook_likeboxcountview_caret_height = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int com_facebook_likeboxcountview_caret_width = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int com_facebook_likeboxcountview_text_padding = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int com_facebook_likeboxcountview_text_size = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int com_facebook_likeview_edge_padding = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int com_facebook_likeview_internal_padding = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int com_facebook_likeview_text_size = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int com_facebook_profilepictureview_preset_size_large = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_profilepictureview_preset_size_normal = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int com_facebook_profilepictureview_preset_size_small = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int com_facebook_share_button_compound_drawable_padding = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int com_facebook_share_button_padding_bottom = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int com_facebook_share_button_padding_left = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int com_facebook_share_button_padding_right = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int com_facebook_share_button_padding_top = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int com_facebook_share_button_text_size = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int com_facebook_tooltip_horizontal_padding = 2131099666;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int com_facebook_button_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int com_facebook_button_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int com_facebook_button_like_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int com_facebook_button_like_icon_selected = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_facebook_button_login_silver_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_facebook_button_send_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_facebook_button_send_icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_close = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_profile_picture_blank_portrait = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_profile_picture_blank_square = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_tooltip_black_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_tooltip_black_bottomnub = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_tooltip_black_topnub = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_tooltip_black_xout = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_tooltip_blue_background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_tooltip_blue_bottomnub = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_tooltip_blue_topnub = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_tooltip_blue_xout = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_menu_refresh = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Icon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int messenger_bubble_large_blue = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int messenger_bubble_large_white = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int messenger_bubble_small_blue = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int messenger_bubble_small_white = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int messenger_button_blue_bg_round = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int messenger_button_blue_bg_selector = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int messenger_button_send_round_shadow = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int messenger_button_white_bg_round = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int messenger_button_white_bg_selector = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000c
			public const int automatic = 2131296268;
			
			// aapt resource value: 0x7f090006
			public const int bottom = 2131296262;
			
			// aapt resource value: 0x7f090003
			public const int box_count = 2131296259;
			
			// aapt resource value: 0x7f090021
			public const int btnAddTask = 2131296289;
			
			// aapt resource value: 0x7f090020
			public const int btnDelete = 2131296288;
			
			// aapt resource value: 0x7f09001e
			public const int btnSave = 2131296286;
			
			// aapt resource value: 0x7f090004
			public const int button = 2131296260;
			
			// aapt resource value: 0x7f090009
			public const int center = 2131296265;
			
			// aapt resource value: 0x7f09001d
			public const int chkDone = 2131296285;
			
			// aapt resource value: 0x7f090014
			public const int com_facebook_body_frame = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int com_facebook_button_xout = 2131296278;
			
			// aapt resource value: 0x7f090012
			public const int com_facebook_fragment_container = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int com_facebook_login_activity_progress_bar = 2131296275;
			
			// aapt resource value: 0x7f090018
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131296280;
			
			// aapt resource value: 0x7f090017
			public const int com_facebook_tooltip_bubble_view_text_body = 2131296279;
			
			// aapt resource value: 0x7f090015
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131296277;
			
			// aapt resource value: 0x7f09001c
			public const int description = 2131296284;
			
			// aapt resource value: 0x7f09000d
			public const int display_always = 2131296269;
			
			// aapt resource value: 0x7f090007
			public const int inline = 2131296263;
			
			// aapt resource value: 0x7f09000f
			public const int large = 2131296271;
			
			// aapt resource value: 0x7f09000a
			public const int left = 2131296266;
			
			// aapt resource value: 0x7f090019
			public const int login_button = 2131296281;
			
			// aapt resource value: 0x7f090022
			public const int lstTasks = 2131296290;
			
			// aapt resource value: 0x7f09001a
			public const int messenger_send_button = 2131296282;
			
			// aapt resource value: 0x7f09000e
			public const int never_display = 2131296270;
			
			// aapt resource value: 0x7f090010
			public const int normal = 2131296272;
			
			// aapt resource value: 0x7f090000
			public const int open_graph = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int page = 2131296257;
			
			// aapt resource value: 0x7f09000b
			public const int right = 2131296267;
			
			// aapt resource value: 0x7f09001f
			public const int row = 2131296287;
			
			// aapt resource value: 0x7f090011
			public const int small = 2131296273;
			
			// aapt resource value: 0x7f090005
			public const int standard = 2131296261;
			
			// aapt resource value: 0x7f090023
			public const int synchronize = 2131296291;
			
			// aapt resource value: 0x7f09001b
			public const int title = 2131296283;
			
			// aapt resource value: 0x7f090008
			public const int top = 2131296264;
			
			// aapt resource value: 0x7f090002
			public const int unknown = 2131296258;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int com_facebook_activity_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int com_facebook_login_fragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int com_facebook_tooltip_bubble = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int messenger_button_send_blue_large = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int messenger_button_send_blue_round = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int messenger_button_send_blue_small = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int messenger_button_send_white_large = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int messenger_button_send_white_round = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int messenger_button_send_white_small = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int todo_detail_layout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int todo_layout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int home_menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040012
			public const int ApplicationName = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int Hello = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int app_id = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int app_name = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int cancelled = 2130968597;
			
			// aapt resource value: 0x7f040000
			public const int com_facebook_image_download_unknown_error = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int com_facebook_internet_permission_error_message = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int com_facebook_internet_permission_error_title = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int com_facebook_like_button_liked = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int com_facebook_like_button_not_liked = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int com_facebook_loading = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int com_facebook_loginview_cancel_action = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int com_facebook_loginview_log_in_button = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int com_facebook_loginview_log_in_button_long = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int com_facebook_loginview_log_out_action = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int com_facebook_loginview_log_out_button = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int com_facebook_loginview_logged_in_as = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int com_facebook_loginview_logged_in_using_facebook = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int com_facebook_send_button_text = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int com_facebook_share_button_text = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int com_facebook_tooltip_default = 2130968591;
			
			// aapt resource value: 0x7f04001b
			public const int error = 2130968603;
			
			// aapt resource value: 0x7f040022
			public const int exception = 2130968610;
			
			// aapt resource value: 0x7f040018
			public const int hello_user = 2130968600;
			
			// aapt resource value: 0x7f040010
			public const int messenger_send_button_text = 2130968592;
			
			// aapt resource value: 0x7f04001f
			public const int no_friends_selected = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int no_place_selected = 2130968608;
			
			// aapt resource value: 0x7f040017
			public const int ok = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int permission_not_granted = 2130968598;
			
			// aapt resource value: 0x7f04001d
			public const int photo_post = 2130968605;
			
			// aapt resource value: 0x7f040021
			public const int pick_seattle_place = 2130968609;
			
			// aapt resource value: 0x7f04001c
			public const int status_update = 2130968604;
			
			// aapt resource value: 0x7f040019
			public const int success = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int successfully_posted_post = 2130968602;
			
			// aapt resource value: 0x7f040023
			public const int synchronize = 2130968611;
			
			// aapt resource value: 0x7f04001e
			public const int you_picked = 2130968606;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MessengerButton = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MessengerButton_Blue = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int MessengerButton_Blue_Large = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int MessengerButton_Blue_Small = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int MessengerButton_White = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int MessengerButton_White_Large = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int MessengerButton_White_Small = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int MessengerButtonText = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int MessengerButtonText_Blue = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int MessengerButtonText_Blue_Large = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int MessengerButtonText_Blue_Small = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int MessengerButtonText_White = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int MessengerButtonText_White_Large = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int MessengerButtonText_White_Small = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int com_facebook_button = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int com_facebook_button_like = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int com_facebook_button_send = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int com_facebook_button_share = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int com_facebook_loginview_default_style = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int com_facebook_loginview_silver_style = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int tooltip_bubble_text = 2131165204;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] com_facebook_like_view = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 4
			public const int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_com_facebook_foreground_color = 0;
			
			// aapt resource value: 5
			public const int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_com_facebook_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_com_facebook_object_type = 2;
			
			// aapt resource value: 3
			public const int com_facebook_like_view_com_facebook_style = 3;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_com_facebook_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_com_facebook_login_text = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_com_facebook_logout_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_com_facebook_tooltip_mode = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_com_facebook_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
